profile: cover.out

local-prefix: "github.com/PixoVR/pixo-platform-operator"

threshold:
#  file: 88

#  package: 88

  total: 81

exclude:
  paths:
    - ^api/v1/zz_generated.*
    - ^internal/controller/setup.go
    - ^cmd
