---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pixo-secret-store
  namespace: system
spec:
  provider:
    gcpsm:
      projectID: apex-dev-app-project

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pixo-platform-credentials
  namespace: system
spec:
  data:
    - remoteRef:
        key: pixo-platform-superadmin-username
      secretKey: username
    - remoteRef:
        key: pixo-platform-superadmin-password
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: platform-operator-pixo-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pixo-platform-credentials