# permissions for end users to edit pixoserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pixoserviceaccount-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: platform-operator
    app.kubernetes.io/part-of: platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: pixoserviceaccount-editor-role
rules:
- apiGroups:
  - platform.pixovr.com
  resources:
  - pixoserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.pixovr.com
  resources:
  - pixoserviceaccounts/status
  verbs:
  - get
