---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.pixovr.com
  resources:
  - pixoserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.pixovr.com
  resources:
  - pixoserviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - platform.pixovr.com
  resources:
  - pixoserviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.pixovr.com
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
