apiVersion: platform.pixovr.com/v1
kind: PixoServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pixoserviceaccount
    app.kubernetes.io/instance: pixoserviceaccount-sample
    app.kubernetes.io/part-of: platform-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: platform-operator
  name: pixoserviceaccount-sample
spec:
  firstName: "John"
  lastName: "Doe"
  orgId: 1
  role: "admin"
