apiVersion: platform.pixovr.com/v1
kind: PixoServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pixoserviceaccount
    app.kubernetes.io/instance: pixoserviceaccount-sample
    app.kubernetes.io/part-of: platform-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: platform-operator
  name: pixoserviceaccount-sample
spec:
  firstName: "John"
  lastName: "Doe"
  orgId: 1
  role: "admin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixoserviceaccount-sample
  annotations:
    platform.pixovr.com/service-account-name: pixoserviceaccount-sample
  labels:
    app: pixoserviceaccount-sample
spec:
    replicas: 1
    selector:
      matchLabels:
        app: pixoserviceaccount-sample
    template:
      metadata:
        labels:
          app: pixoserviceaccount-sample
      spec:
        containers:
        - name: pixoserviceaccount-sample
          image: "nginx:1.14.2"
          ports:
          - containerPort: 80